input-directory: "test-files/input"
logging:
  level:
    root: INFO
    com:
      azure:
        spring:
          example:
            file:
              processing: DEBUG
    org:
      springframework:
        integration:
          file: DEBUG
spring:
  cloud:
    azure:
      eventhubs:
        connection-string:
        event-hub-name:
  config:
    import: develop.yml